// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251129230810_AddSeuilAlerte")]
    partial class AddSeuilAlerte
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Domain.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CanalCommunication")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CredentialsDevice")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<DateTime>("DateInstallation")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstActif")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LocalisationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlDevice")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LocalisationId");

                    b.ToTable("Devices");

                    b.HasDiscriminator<string>("DeviceType").HasValue("Device");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entities.Localisation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Localisations");
                });

            modelBuilder.Entity("Domain.Entities.Releve", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateHeure")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SondeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeReleve")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valeur")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SondeId", "DateHeure")
                        .HasDatabaseName("IX_Releves_SondeId_DateHeure");

                    b.ToTable("Releves");
                });

            modelBuilder.Entity("Domain.Entities.SeuilAlerte", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<bool>("EstActif")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SondeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeAlerte")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeSeuil")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valeur")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SondeId")
                        .HasDatabaseName("IX_SeuilsAlerte_SondeId");

                    b.ToTable("SeuilsAlerte");
                });

            modelBuilder.Entity("Domain.Entities.SystemePartenaire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<bool>("EstActif")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstAppelant")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstAppele")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordChiffre")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHashAcces")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlBase")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("UsernameAcces")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("UsernameAppel")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UsernameAcces")
                        .HasDatabaseName("IX_SystemesPartenaires_UsernameAcces");

                    b.ToTable("SystemesPartenaires");
                });

            modelBuilder.Entity("Domain.Entities.UniteMesure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeSonde")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TypeSonde", "Symbole")
                        .IsUnique()
                        .HasDatabaseName("IX_UnitesMesures_TypeSonde_Symbole");

                    b.ToTable("UnitesMesures");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstActif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Username");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Entities.Actionneur", b =>
                {
                    b.HasBaseType("Domain.Entities.Device");

                    b.Property<int>("TypeActionneur")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Actionneur");
                });

            modelBuilder.Entity("Domain.Entities.Sonde", b =>
                {
                    b.HasBaseType("Domain.Entities.Device");

                    b.Property<int>("TypeSonde")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UniteMesureId")
                        .HasColumnType("TEXT");

                    b.HasIndex("UniteMesureId");

                    b.HasDiscriminator().HasValue("Sonde");
                });

            modelBuilder.Entity("Domain.Entities.Device", b =>
                {
                    b.HasOne("Domain.Entities.Localisation", "Localisation")
                        .WithMany()
                        .HasForeignKey("LocalisationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Localisation");
                });

            modelBuilder.Entity("Domain.Entities.Releve", b =>
                {
                    b.HasOne("Domain.Entities.Sonde", "Sonde")
                        .WithMany()
                        .HasForeignKey("SondeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sonde");
                });

            modelBuilder.Entity("Domain.Entities.SeuilAlerte", b =>
                {
                    b.HasOne("Domain.Entities.Sonde", "Sonde")
                        .WithMany()
                        .HasForeignKey("SondeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sonde");
                });

            modelBuilder.Entity("Domain.Entities.Sonde", b =>
                {
                    b.HasOne("Domain.Entities.UniteMesure", "UniteMesure")
                        .WithMany()
                        .HasForeignKey("UniteMesureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UniteMesure");
                });
#pragma warning restore 612, 618
        }
    }
}
